### ISSUE TITLE
Mechs being replaced in Co-op

### ISSUE THREAD

**Issue by thehunter97** [MagnumForceGB/MercTech#12]
When other players modify mechs, they lose keybinding options even on reload. Removing and replacing the weapons fixes the issue for the keybinds, but when storing the mechs in cold storage, they turn into a different mech. Not sure if its the same mech for everyone, but for me it turns into the Highlander HGN-732 with varying stages of loadouts and damage.

**Comment by RikKoningen** [comment]
I'm having the same issue, except for me the mech turns into an Awesome 8Q. Been troubleshooting for a bit now and have yet to find anything of note to fix it.
